//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.27 at 03:43:08 PM CEST 
//


package com.bbva.kyof.vega.config.general;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AutoDiscoveryConfig complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AutoDiscoveryConfig">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="time_to_live" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="refresh_interval" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="node_type" type="{http://www.bbva.com/zeromq/config}NodeType" minOccurs="0"/>
 *         &lt;element name="transport_media" type="{http://www.bbva.com/zeromq/config}TransportMediaType" minOccurs="0"/>
 *         &lt;element name="addresses" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="reconnection_interval" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="reconnection_tries" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AutoDiscoveryConfig", propOrder = {
    "timeToLive",
    "refreshInterval",
    "nodeType",
    "transportMedia",
    "addresses",
    "reconnectionInterval",
    "reconnectionTries"
})
public class AutoDiscoveryConfig {

    @XmlElement(name = "time_to_live")
    protected Integer timeToLive;
    @XmlElement(name = "refresh_interval")
    protected Long refreshInterval;
    @XmlElement(name = "node_type")
    protected NodeType nodeType;
    @XmlElement(name = "transport_media")
    protected TransportMediaType transportMedia;
    protected String addresses;
    @XmlElement(name = "reconnection_interval")
    protected Integer reconnectionInterval;
    @XmlElement(name = "reconnection_tries")
    protected Integer reconnectionTries;

    /**
     * Gets the value of the timeToLive property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTimeToLive() {
        return timeToLive;
    }

    /**
     * Sets the value of the timeToLive property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTimeToLive(Integer value) {
        this.timeToLive = value;
    }

    /**
     * Gets the value of the refreshInterval property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getRefreshInterval() {
        return refreshInterval;
    }

    /**
     * Sets the value of the refreshInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setRefreshInterval(Long value) {
        this.refreshInterval = value;
    }

    /**
     * Gets the value of the nodeType property.
     * 
     * @return
     *     possible object is
     *     {@link NodeType }
     *     
     */
    public NodeType getNodeType() {
        return nodeType;
    }

    /**
     * Sets the value of the nodeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link NodeType }
     *     
     */
    public void setNodeType(NodeType value) {
        this.nodeType = value;
    }

    /**
     * Gets the value of the transportMedia property.
     * 
     * @return
     *     possible object is
     *     {@link TransportMediaType }
     *     
     */
    public TransportMediaType getTransportMedia() {
        return transportMedia;
    }

    /**
     * Sets the value of the transportMedia property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransportMediaType }
     *     
     */
    public void setTransportMedia(TransportMediaType value) {
        this.transportMedia = value;
    }

    /**
     * Gets the value of the addresses property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddresses() {
        return addresses;
    }

    /**
     * Sets the value of the addresses property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddresses(String value) {
        this.addresses = value;
    }

    /**
     * Gets the value of the reconnectionInterval property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getReconnectionInterval() {
        return reconnectionInterval;
    }

    /**
     * Sets the value of the reconnectionInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setReconnectionInterval(Integer value) {
        this.reconnectionInterval = value;
    }

    /**
     * Gets the value of the reconnectionTries property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getReconnectionTries() {
        return reconnectionTries;
    }

    /**
     * Sets the value of the reconnectionTries property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setReconnectionTries(Integer value) {
        this.reconnectionTries = value;
    }

}
