//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.27 at 03:43:08 PM CEST 
//


package com.bbva.kyof.vega.config.general;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InstanceConfig complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InstanceConfig">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="auto_discovery" type="{http://www.bbva.com/zeromq/config}AutoDiscoveryConfig" minOccurs="0"/>
 *         &lt;element name="pub_topic" type="{http://www.bbva.com/zeromq/config}PubTopicConfig" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="sub_topic" type="{http://www.bbva.com/zeromq/config}SubTopicConfig" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="req_topic" type="{http://www.bbva.com/zeromq/config}ReqTopicConfig" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="resp_topic" type="{http://www.bbva.com/zeromq/config}RespTopicConfig" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="pub_socket_schema" type="{http://www.bbva.com/zeromq/config}PubSocketSchema" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="sub_socket_schema" type="{http://www.bbva.com/zeromq/config}SubSocketSchema" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="req_socket_schema" type="{http://www.bbva.com/zeromq/config}ReqSocketSchema" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="resp_socket_schema" type="{http://www.bbva.com/zeromq/config}RespSocketSchema" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="use_native_zeromq_filtering" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InstanceConfig", propOrder = {
    "autoDiscovery",
    "pubTopic",
    "subTopic",
    "reqTopic",
    "respTopic",
    "pubSocketSchema",
    "subSocketSchema",
    "reqSocketSchema",
    "respSocketSchema"
})
public class InstanceConfig {

    @XmlElement(name = "auto_discovery")
    protected AutoDiscoveryConfig autoDiscovery;
    @XmlElement(name = "pub_topic")
    protected List<PubTopicConfig> pubTopic;
    @XmlElement(name = "sub_topic")
    protected List<SubTopicConfig> subTopic;
    @XmlElement(name = "req_topic")
    protected List<ReqTopicConfig> reqTopic;
    @XmlElement(name = "resp_topic")
    protected List<RespTopicConfig> respTopic;
    @XmlElement(name = "pub_socket_schema")
    protected List<PubSocketSchema> pubSocketSchema;
    @XmlElement(name = "sub_socket_schema")
    protected List<SubSocketSchema> subSocketSchema;
    @XmlElement(name = "req_socket_schema")
    protected List<ReqSocketSchema> reqSocketSchema;
    @XmlElement(name = "resp_socket_schema")
    protected List<RespSocketSchema> respSocketSchema;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "use_native_zeromq_filtering")
    protected Boolean useNativeZeromqFiltering;

    /**
     * Gets the value of the autoDiscovery property.
     * 
     * @return
     *     possible object is
     *     {@link AutoDiscoveryConfig }
     *     
     */
    public AutoDiscoveryConfig getAutoDiscovery() {
        return autoDiscovery;
    }

    /**
     * Sets the value of the autoDiscovery property.
     * 
     * @param value
     *     allowed object is
     *     {@link AutoDiscoveryConfig }
     *     
     */
    public void setAutoDiscovery(AutoDiscoveryConfig value) {
        this.autoDiscovery = value;
    }

    /**
     * Gets the value of the pubTopic property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pubTopic property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPubTopic().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PubTopicConfig }
     * 
     * 
     */
    public List<PubTopicConfig> getPubTopic() {
        if (pubTopic == null) {
            pubTopic = new ArrayList<PubTopicConfig>();
        }
        return this.pubTopic;
    }

    /**
     * Gets the value of the subTopic property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the subTopic property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubTopic().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SubTopicConfig }
     * 
     * 
     */
    public List<SubTopicConfig> getSubTopic() {
        if (subTopic == null) {
            subTopic = new ArrayList<SubTopicConfig>();
        }
        return this.subTopic;
    }

    /**
     * Gets the value of the reqTopic property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reqTopic property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReqTopic().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReqTopicConfig }
     * 
     * 
     */
    public List<ReqTopicConfig> getReqTopic() {
        if (reqTopic == null) {
            reqTopic = new ArrayList<ReqTopicConfig>();
        }
        return this.reqTopic;
    }

    /**
     * Gets the value of the respTopic property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the respTopic property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRespTopic().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RespTopicConfig }
     * 
     * 
     */
    public List<RespTopicConfig> getRespTopic() {
        if (respTopic == null) {
            respTopic = new ArrayList<RespTopicConfig>();
        }
        return this.respTopic;
    }

    /**
     * Gets the value of the pubSocketSchema property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pubSocketSchema property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPubSocketSchema().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PubSocketSchema }
     * 
     * 
     */
    public List<PubSocketSchema> getPubSocketSchema() {
        if (pubSocketSchema == null) {
            pubSocketSchema = new ArrayList<PubSocketSchema>();
        }
        return this.pubSocketSchema;
    }

    /**
     * Gets the value of the subSocketSchema property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the subSocketSchema property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubSocketSchema().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SubSocketSchema }
     * 
     * 
     */
    public List<SubSocketSchema> getSubSocketSchema() {
        if (subSocketSchema == null) {
            subSocketSchema = new ArrayList<SubSocketSchema>();
        }
        return this.subSocketSchema;
    }

    /**
     * Gets the value of the reqSocketSchema property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reqSocketSchema property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReqSocketSchema().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReqSocketSchema }
     * 
     * 
     */
    public List<ReqSocketSchema> getReqSocketSchema() {
        if (reqSocketSchema == null) {
            reqSocketSchema = new ArrayList<ReqSocketSchema>();
        }
        return this.reqSocketSchema;
    }

    /**
     * Gets the value of the respSocketSchema property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the respSocketSchema property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRespSocketSchema().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RespSocketSchema }
     * 
     * 
     */
    public List<RespSocketSchema> getRespSocketSchema() {
        if (respSocketSchema == null) {
            respSocketSchema = new ArrayList<RespSocketSchema>();
        }
        return this.respSocketSchema;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the useNativeZeromqFiltering property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isUseNativeZeromqFiltering() {
        if (useNativeZeromqFiltering == null) {
            return false;
        } else {
            return useNativeZeromqFiltering;
        }
    }

    /**
     * Sets the value of the useNativeZeromqFiltering property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUseNativeZeromqFiltering(Boolean value) {
        this.useNativeZeromqFiltering = value;
    }

}
