//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.27 at 03:43:08 PM CEST 
//


package com.bbva.kyof.vega.config.general;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RespSocketSchema complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RespSocketSchema">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="min_port" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="max_port" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="max_num_ports" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="transport_media" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="transport_interface" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RespSocketSchema", propOrder = {
    "minPort",
    "maxPort",
    "maxNumPorts",
    "transportMedia",
    "transportInterface"
})
public class RespSocketSchema {

    @XmlElement(name = "min_port")
    protected int minPort;
    @XmlElement(name = "max_port")
    protected Integer maxPort;
    @XmlElement(name = "max_num_ports", defaultValue = "1")
    protected Integer maxNumPorts;
    @XmlElement(name = "transport_media", defaultValue = "tcp")
    protected String transportMedia;
    @XmlElement(name = "transport_interface", defaultValue = "*")
    protected String transportInterface;
    @XmlAttribute(name = "name", required = true)
    protected String name;

    /**
     * Gets the value of the minPort property.
     * 
     */
    public int getMinPort() {
        return minPort;
    }

    /**
     * Sets the value of the minPort property.
     * 
     */
    public void setMinPort(int value) {
        this.minPort = value;
    }

    /**
     * Gets the value of the maxPort property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMaxPort() {
        return maxPort;
    }

    /**
     * Sets the value of the maxPort property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxPort(Integer value) {
        this.maxPort = value;
    }

    /**
     * Gets the value of the maxNumPorts property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMaxNumPorts() {
        return maxNumPorts;
    }

    /**
     * Sets the value of the maxNumPorts property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxNumPorts(Integer value) {
        this.maxNumPorts = value;
    }

    /**
     * Gets the value of the transportMedia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransportMedia() {
        return transportMedia;
    }

    /**
     * Sets the value of the transportMedia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransportMedia(String value) {
        this.transportMedia = value;
    }

    /**
     * Gets the value of the transportInterface property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransportInterface() {
        return transportInterface;
    }

    /**
     * Sets the value of the transportInterface property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransportInterface(String value) {
        this.transportInterface = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
