//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.27 at 03:43:08 PM CEST 
//


package com.bbva.kyof.vega.config.general;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TransportMediaType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TransportMediaType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="tcp-ip"/>
 *     &lt;enumeration value="multicast"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TransportMediaType")
@XmlEnum
public enum TransportMediaType {

    @XmlEnumValue("tcp-ip")
    TCP_IP("tcp-ip"),
    @XmlEnumValue("multicast")
    MULTICAST("multicast");
    private final String value;

    TransportMediaType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TransportMediaType fromValue(String v) {
        for (TransportMediaType c: TransportMediaType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
